site_name: 飘 | 知识仓库

theme:
  name: 'material'

nav:
  - 首页: index.md
  - 技术仓库:
    - MySQL 数据库: computer/MySQL数据库.md
    - Python 库相关操作: computer/Python库相关操作.md
  - 工具仓库:
    - MkDocs 常用操作: tool/MkDocs常用操作.md
    - Hexo 常用操作: tool/Hexo常用操作.md
  - 慕课笔记:
    - 计算机速成课: computer/CrashCourseComputerScience.md
  - 家电知识:
    - 空调爆炸图: mess/aircondition.md